### ISSUE TITLE
XLC build

### ISSUE THREAD

**Issue by BKdilse** [Bathmat/nodejs-pool#1]
Thanks for opening up Issues @Bathmat.

Your deploy bash script doesn't have the details on the daemon to use.  When I use the coin repos daemon I cannot get the pool to work.  I'll send actual errors shortly when I get to my PC.

Could you please clarify which daemon I am suppose to use, along with any additional settings.
The forknote site states the Leviar config doesn't work.  Confussed.

I'm rebuilding my server, due to too many changes I made for testing.

**Comment by Bathmat** [comment]
The deployment installs Forknote since most of the coins can use that; however, XLC appears to be it's own special case. I am currently using the latest commit from: https://github.com/leviarcoin/leviarcoin-src

Depending on when you installed, your configuration might have the wrong utils for XLC. If you are seeing `Failed to get block_header` errors, then it is a utils issue (most likely). I just updated it today when I noticed it after you mentioned it. Go into /lib/coins/xlc.js and make sure (or change) line 3 to forknote-util: `const cnUtil = require('forknote-util');`

There is another change required for XLC in blockManger.js to prevent all blocks from being marked orphaned incorrectly. Change line 406 in blockManger.js to: ` global.support.rpcDaemon('getblockheaderbyheight', {"height": row.height + 1}, function (body) {`

**Comment by BKdilse** [comment]
I'm rebuilding server, due to too many changes during troubleshooting.
I'll give the above a go.  I can see your update to xlc.js, so I'll just make the blockManager.js change.

Thanks for the pointers so far :)

I've noticed other files have const cnUtil = require('cryptonote-util');  , such as api.js.  Should that remain as is?

**Comment by Bathmat** [comment]
Yeah, no need to change that one. The api is just looking at address decode which _should be_ the same for both forknote and cryptonote. I haven't changed that one in any of my builds and haven't seen any issues.

**Comment by BKdilse** [comment]
OK Cool, I've give it a go.

**Comment by BKdilse** [comment]
Re-installed this from scratch, and still have issues.  This is what I do, and what happens:

Stop all modules, for clean start: **pm2 stop all**

Start Daemon: **/usr/local/src/leviarcoin-src/src/leviarcoind --rpc-bind-ip 0.0.0.0**
2018-Mar-06 23:50:55.461128 INFO    leviarcoin v2.1.3 Beryllium
2018-Mar-06 23:50:55.461262 INFO    Module folder: /usr/local/src/leviarcoin-src/src/leviarcoind
2018-Mar-06 23:50:55.461416 INFO    Opening DB in /home/locadmin/.leviarcoin/DB
2018-Mar-06 23:50:57.048427 INFO    DB opened in /home/locadmin/.leviarcoin/DB
2018-Mar-06 23:50:57.051221 INFO    Initializing core...
2018-Mar-06 23:50:57.088966 INFO    DB has more blocks than blockchain storage, cutting from block index: 326359
2018-Mar-06 23:50:57.089038 INFO    Cutting root segment from index 326359
2018-Mar-06 23:50:57.120488 INFO    Core initialized OK
2018-Mar-06 23:50:57.120582 INFO    Initializing p2p server...
2018-Mar-06 23:50:57.121018 INFO    Binding on 0.0.0.0:18001
2018-Mar-06 23:50:57.121095 INFO    Net service binded on 0.0.0.0:18001
2018-Mar-06 23:50:57.121126 INFO    Attempting to add IGD port mapping.
2018-Mar-06 23:50:57.128340 INFO    UPnP device was found but not recoginzed as IGD.
2018-Mar-06 23:50:57.128409 INFO    P2p server initialized OK
2018-Mar-06 23:50:57.128807 INFO    Starting core rpc server on address 0.0.0.0:19001
2018-Mar-06 23:50:57.128883 INFO    Core rpc server started ok
2018-Mar-06 23:50:57.128923 INFO    Starting p2p net loop...
2018-Mar-06 23:50:57.128945 INFO    Starting node_server
2018-Mar-06 23:51:07.484038 INFO    [69.85.85.233:18001 OUT] Sync data returned unknown top block: 326359 -> 326366 [7 blocks (0 days) behind]
2018-Mar-06 23:51:07.484038 INFO    SYNCHRONIZATION started
2018-Mar-06 23:51:08.563780 INFO    [69.85.85.233:18001 OUT] SYNCHRONIZED OK
2018-Mar-06 23:51:08.563846 INFO
2018-Mar-06 23:51:08.563846 INFO    **********************************************************************
2018-Mar-06 23:51:08.563846 INFO    You are now synchronized with the network. You may now start simplewallet.
2018-Mar-06 23:51:08.563846 INFO
2018-Mar-06 23:51:08.563846 INFO    Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.
2018-Mar-06 23:51:08.563846 INFO    Otherwise, you will possibly need to synchronize the blockchain again.
2018-Mar-06 23:51:08.563846 INFO
2018-Mar-06 23:51:08.563846 INFO    Use "help" command to see the list of available commands.
2018-Mar-06 23:51:08.563846 INFO    **********************************************************************

Start Wallet RPC: **/usr/local/src/leviarcoin-src/src/simplewallet --rpc-bind-port 19002 --wallet-file Pool --password 'xxxxxxxxx'**
2018-Mar-06 23:52:27.855892 INFO    leviarcoin wallet v2.1.3 Beryllium
2018-Mar-06 23:52:27.856263 INFO    Loading wallet...
2018-Mar-06 23:52:27.928097 INFO    available balance: 0.00000000, locked amount: 0.00000000
2018-Mar-06 23:52:27.928309 INFO    Loaded ok
2018-Mar-06 23:52:27.928431 INFO    Starting wallet rpc server

No further output from wallet

Looks good so far... but problem start below:

Start modules: **pm2 start all**
This all start up

Daemon dies with message **Segmentation fault (core dumped)**

Wallet show messages:
2018-Mar-06 23:53:50.832818 DEBUG   Incoming connection from 127.0.0.1:34810
2018-Mar-06 23:53:50.944763 DEBUG   Closing connection from 127.0.0.1:34810 total=1
2018-Mar-06 23:53:50.958275 DEBUG   Incoming connection from 127.0.0.1:34822
2018-Mar-06 23:53:51.030479 DEBUG   Closing connection from 127.0.0.1:34822 total=1

There are errors being reported in blockManager and worker logs, all others appear fine:
**blockManager**
2018-03-06 23:59 +00:00: TypeError: Cannot read property 'block_header' of undefined
    at /home/locadmin/nodejs-pool/lib/blockManager.js:21:36
    at /home/locadmin/nodejs-pool/lib/support.js:100:24
    at Object.parseBody (/home/locadmin/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/locadmin/nodejs-pool/node_modules/request-json/main.js:148:26)
    at self.callback (/home/locadmin/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/locadmin/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:346:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2018-03-06 23:59 +00:00: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":19001}
2018-03-06 23:59 +00:00: Upstream error from the block daemon.  Resetting scanner due to: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":19001}
2018-03-06 23:59 +00:00: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":19001}
Upstream error from the block daemon.  Resetting scanner due to: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":19001}
2018-03-06 23:59 +00:00: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":19001}

**Worker**
2018-03-06 23:59 +00:00: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":19001}
TypeError: Cannot read property 'block_header' of undefined
    at /home/locadmin/nodejs-pool/lib/worker.js:448:31
    at /home/locadmin/nodejs-pool/lib/support.js:100:24
    at Object.parseBody (/home/locadmin/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/locadmin/nodejs-pool/node_modules/request-json/main.js:148:26)
    at self.callback (/home/locadmin/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/locadmin/nodejs-pool/node_modules/request-json/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2018-03-06 23:59 +00:00: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":19001}

Only other thing I've noticed is that the modules disappear after a reboot.  All apart from **pm2-logrotate**

And the Pool Webpage doesn't load, page cannot be display.

I have build various other pools, and have never had these issue.

Any idea where the issue might be?

**Comment by Bathmat** [comment]
Any reason you set `--rpc-bind-ip 0.0.0.0` for the daemon? Maybe try without that?

You say you've done other pools, were they nodejs?

Also, have you tried `pm2 kill` then `source ~/.bashrc` then start all pm2 modules again?

**Comment by BKdilse** [comment]
I've used rpc bind ip on all other pools as instructed.  I've used 0.0.0.0 instead of 127.0.0.1 so my wallet on the client PC can sync with the node.

All other pools are nodejs, monero forks.

I haven't tried the kill command.  I'll give it a go.

**Comment by BKdilse** [comment]
Something has gone wrong with this re-build.  Tried kill and source....  commands, added modules back in.

Reboot, and modules are gone again.  Also, the Pool UI does not work at all, which is weird.  This was not a problem previously, but I didn't take full notes on how I built it.

Now attempting another rebuild, and will refer to notes from my other pools, in case I have missed a step,

**Comment by BKdilse** [comment]
@Bathmat I will use your deploy.bash, along with the manual changes you have already advised off, and DB changes for XLC coin.

I take it I do not need these 2, as i'm not using the forknote daemon?
**sudo git clone https://github.com/forknote/forknote.git 
sudo git clone https://github.com/forknote/configs.git**

**Comment by Bathmat** [comment]
Yeah, you don't need those for XLC.

XLC is a forknote coin, so in theory you could use the forknote daemon/wallet with the XLC, but XLC changed some stuff in their code so that I'm not 100% sure that it would be compatible. And honestly, I haven't been bothered enough to try it.

**Comment by BKdilse** [comment]
I did try forknote daemon last week, and it didn't work.

OK, I've found a few differences between your bash script and my manual one...  I'm missing libssl-dev (may not be the cause of issues, but I'll add it this time).

Also, I was missing a chunk of commands from the Caddy install section (must have cut it rather than copy, when pasting into Putty... DOH !!!).  This must e why Pool UI wasn't working.

Keep you posted...  hopefully, I'll have a running pool tonight :)

**Comment by BKdilse** [comment]
Well...  got the damn thing up and running now...

It was the missing bits of lines in my rough guide.  PM2 is also retaining settings, so must have cut bits out too LOL.

The Daemon did initially crash out as before, but after a few attempts it has stabilized.

I'll monitor this over the next few days.

Thanks for you help on this.

**Comment by BKdilse** [comment]
Found an issue with payout:

4|payments | 2018-03-07 23:29 +00:00: Issue making payments{"code":-4,"message":"Wrong amount"}
4|payments | Will not make more payments until the payment daemon is restarted!

Tried a pm2 restart payments, and makes no difference.

Any ideas?

**Comment by Bathmat** [comment]
Check in MYSQL config table for an item labeled "payout, fee, Atomic units of coin to use ass a fee" (it's usually line 71 when I install). Make sure that it is set to have less 0's than the "sigDivisor, Divisor for turning coin into human readable amounts". 

I usually set it to the DEFAULT_DUST_THRESHOLD of the coin from the CryptoNoteConfig.h, which for Leviar is 1000000.

EDIT: I meant to say above: set it to the MINIMUM_FEE for the coin. It's usually the same as the DEFAULT_DUST_THRESHOLD though.

Might also be worth double checking the mixin value in MYSQL. I set it to 0 for Forknote coins. It'll still submit payments with 1 mixin.

**Comment by BKdilse** [comment]
payout, fee adjusted from 10000000000 to 1000000.

I originally set mixIn in SQL to 1 (as per coinConfig.json), i've now changed it to 0.
Do I need to change it in coinConfig.json as well?

Do I then do a pm2 restart payments?

**Comment by Bathmat** [comment]
As far as I can tell, changing the mixin value in the coinConfig does't affect anything; however, feel free to mess around with it and share the results.

Additionally, there's an extra mixin being added somewhere in the code; i.e., when set to 0 in MYSQL it shows 0 on the payouts page, but actually sends the transaction with 1 mixin. When set to 1, it shows 1 on payments page but sends with 2.

But yeah, pm2 restart payments. If that doesn't work, you can always give it a pm2 restart all.

**Comment by BKdilse** [comment]
Pm2 restart all sorted it out.

I'll leave it running now.  Too many late nights working on this.

Thanks again for your help in getting me going.

I'll provide feedback on any finding.

:)
