### ISSUE TITLE
Nice project 

### ISSUE THREAD

**Issue by mdiersma** [Bathmat/nodejs-pool#4]
I like your project, TRTL in the great Snipa pool .
Got quite far implementing this pool. But getting stuck on some big things.

I see the TRTL net hash... but it's lik 1/3 it should be. Difficulty is showing ok though.
Reward is like 0.0000297x

Is iet possible to get some assistance how to get this properly running ?
Not for nothing offcourse

**Comment by Bathmat** [comment]
Those are defined by poolui. Look there under `/utils/strings.js`
